version: "3.8"
services:
  orion:
    platform: linux/amd64
    image: quay.io/fiware/orion-ld:${ORION_LD_VERSION}
    hostname: orion
    container_name: fiware-orion
    restart: always
    depends_on:
      - mongo-db
      - context
    networks:
      - default
    expose: 
      - "${ORION_LD_PORT}"
    ports:
      - "${ORION_LD_PORT}:${ORION_LD_PORT}"
    environment:
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=orion
      - ORIONLD_TROE_HOST=timescale-db
      - ORIONLD_MONGO_HOST=mongo-db
      - ORIONLD_MULTI_SERVICE=TRUE
      - ORIONLD_DISABLE_FILE_LOG=TRUE
    command: -dbhost mongo-db -logLevel ERROR -troePoolSize 10 -forwarding
    healthcheck:
      test: curl --fail -s http://orion:${ORION_LD_PORT}/version || exit 1
      interval: 10s

  mintaka:
    image: quay.io/fiware/mintaka:${MINTAKA_VERSION}
    hostname: mintaka
    container_name: fiware-mintaka
    restart: always
    depends_on:
      - timescale-db
    environment:
      - DATASOURCES_DEFAULT_HOST=timescale-db
      - DATASOURCES_DEFAULT_USERNAME=orion
      - DATASOURCES_DEFAULT_PASSWORD=orion
      - DATASOURCES_DEFAULT_DATABASE=orion
      - DATASOURCES_DEFAULT_MAXIMUM_POOL_SIZE=2
      - ENDPOINTS_INFO_ENABLED=true
      - ENDPOINTS_INFO_SENSITIVE=false
    expose:
      - "${MINTAKA_PORT}"
    ports:
      - "${MINTAKA_PORT}:${MINTAKA_PORT}"
    networks:
      - default

  timescale-db:
    image: timescale/timescaledb-postgis:${TIMESCALE_VERSION}
    hostname: timescale-db
    container_name: db-timescale
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orion" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 60s
    environment:
      - POSTGRES_USER=orion
      - POSTGRES_PASSWORD=orion
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "log_statement=none"]
    expose:
      - "${TIMESCALE_PORT}"
    ports:
     - "${TIMESCALE_PORT}:${TIMESCALE_PORT}"
    networks:
      - default
    volumes:
      - timescale-db:/var/lib/postgresql/data

  iot-agent:
      image: quay.io/fiware/iotagent-json:${IOTA_JSON_VERSION}
      hostname: iot-agent
      container_name: fiware-iot-agent
      depends_on:
        - mongo-db
        - mosquitto
        - context
      networks:
        - default
      expose:
        - '{IOTA_NORTH_PORT}'
      ports:
        - '${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}' # localhost:4041
      environment:
        - IOTA_CB_HOST=orion #
        - IOTA_CB_PORT=${ORION_LD_PORT} 
        - IOTA_NORTH_PORT=${IOTA_NORTH_PORT}
        - IOTA_REGISTRY_TYPE=mongodb 
        - IOTA_LOG_LEVEL=DEBUG 
        - IOTA_TIMESTAMP=true 
        - IOTA_CB_NGSI_VERSION=ld 
        - IOTA_AUTOCAST=true 
        - IOTA_MONGO_HOST=mongo-db 
        - IOTA_MONGO_PORT=${MONGO_DB_PORT}
        - IOTA_MONGO_DB=iotagentjson 
        - IOTA_MQTT_HOST=mosquitto 
        - IOTA_MQTT_PORT=${MQTT_BROKER_PORT}
        - IOTA_DEFAULT_RESOURCE= #/iot/json # Default is blank. I'm using MQTT so I don't need a resource
        - IOTA_PROVIDER_URL=http://iot-agent:4041
        - IOTA_DEFAULT_TRANSPORT=MQTT
        - IOTA_FALLBACK_TENANT=openiot
        - IOTA_MULTI_CORE=true
        - IOTA_JSON_LD_CONTEXT=http://context:${CONTEXT_PORT}/ngsi-context.jsonld

  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "${MQTT_BROKER_PORT}"
    ports:
      - "${MQTT_BROKER_PORT}:${MQTT_BROKER_PORT}"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  topicbridge:
    image: danny0117/incode-heu-mqtt-topic-bridge:1.1.0
    hostname: topicbridge
    container_name: topicbridge 
    environment:
        - POLAR_H10_API_KEY=${POLAR_H10_API_KEY}
        - MQTT_BROKER_NAME=mosquitto
        - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
    depends_on:
      - mosquitto 

  context: 
    image: danny0117/incode-heu-contextfiles:${CONTEXT_DOCKER_TAG}
    hostname: context
    container_name: context
    expose: 
      - '${CONTEXT_PORT}'
    ports:
      - '${CONTEXT_PORT}:${CONTEXT_PORT}'

  application: 
    image : danny0117/incode-heu-aa3-uc1:${APP_DOCKER_TAG}
    hostname: application
    container_name: application
    expose: 
      - '${APP_PORT}'
    ports:
      - '${APP_PORT}:${APP_PORT}'

  mongo-db:
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "${MONGO_DB_PORT}"
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017
    networks:
      - default
    volumes:
      - mongo-db:/data
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  timescale-db: ~
  mongo-db: ~